### ISSUE TITLE
The format package doesn't escape strings

### ISSUE THREAD

**Issue by icholy** [ulule/loukoum#30]
The `String()` method on builders is completely vulnerable to sql injection.
``` go
package main

import (
	"fmt"
	lk "github.com/ulule/loukoum"
)

func main() {
	fmt.Println(
		lk.Select("*").From("users").Where(
			lk.Condition("name").Equal("' OR 1 == 1 --"),
		).String(),
	)
}
```

output: 
``` sql
SELECT * FROM users WHERE (name = '' OR 1 == 1 --')
```

**Comment by novln** [comment]
Hello,

If you want safety, you should use `lk.Select("*").From("users").Where(...).Prepare()`

`String()` is mainly used for debugging and have a huge footprint (see https://github.com/ulule/loukoum/blob/d6ee7eac818ec74889870fa82dff411ea266463b/builder/builder.go#L26)

Hope that helps.

**Comment by icholy** [comment]
@novln I realise after reading through the code, but that wasn't mentioned anywhere in the docs. Something like that should be front and center, bolded, in a red font.

**Comment by novln** [comment]
Noted :smile: 

I'll do a swipe on the documentation to ensure that this kind of information are shared.
If you find anything that need clarification, don't hesitate.
