### ISSUE TITLE
Slices being spread out into values

### ISSUE THREAD

**Issue by icholy** [ulule/loukoum#34]
What's the use case for this behaviour?

``` go
package main

import (
	"fmt"
	lk "github.com/ulule/loukoum"
)

func main() {
	fmt.Println(
		lk.Insert("foo").Set(
			lk.Pair("a", []int{1, 2, 3}),
		).String(),
	)
}
```

output:

``` text
INSERT INTO foo (a) VALUES (1, 2, 3)
```

Where is `stmt.Array` actually useful?

**Comment by icholy** [comment]
Ok, so I've read through the code and it looks like the problem is that `NewExpression` and `NewArrayExpression` are calling each other recursively. Would you guys be opposed to using reflection to handle the arrays?

**Comment by novln** [comment]
It's definitely a corner case, but we trust loukoum's user to known how to generate a valid SQL query.

However, we could add a type checking to ensure pair's value has a valid type here:
https://github.com/ulule/loukoum/blob/b658af15b7c4b97df2c993875bda0e9fc5cc18fe/loukoum.go#L27

What do you think @thoas & @gillesfabio ?

**Comment by thoas** [comment]
@novln sounds good for me 👍

**Comment by icholy** [comment]
@novln that won't work because `[]byte` is a valid type here.
