### ISSUE TITLE
Examples for joining with 2 columns

### ISSUE THREAD

**Issue by fi0** [ulule/loukoum#52]
How do I create a Join query that uses more than 1 column?

**Comment by novln** [comment]
Could you give me an example with a simple query ?
I'm not familiar with this type of query and besides using logical comparaisons (`AND` & `OR`) I don't find more examples relevant _(or maybe that's it...)_ 

Thank you.

**Comment by fi0** [comment]
I'm trying to build a query with an AND operator
select * from t1 left join t2 on t1.a = t2.a AND t1.b = t2.b

**Comment by novln** [comment]
Perfect :slightly_smiling_face: 
I should be able to start writing an implementation soon.

**Comment by novln** [comment]
@fi0 Don't have much time at this moment, but I don't worry I won't forget this :)
