### ISSUE TITLE
How to Select Exists ?

### ISSUE THREAD

**Issue by ferhatelmas** [ulule/loukoum#62]
How to write following query ?

```sql
SELECT EXISTS (SELECT 1)
```

One try:
```go
lk.Select(lk.Exists(lk.Select("1"))).String()
```

It fails like this:
```sh
panic: loukoum: cannot use stmt.Exists as column
```

I checked tests and it was only tested as a condition. Missing anything ?

**Comment by novln** [comment]
@ferhatelmas I've added support of few expressions for select, hope that helps :slightly_smiling_face: 

https://github.com/ulule/loukoum/blob/dev/builder/select_test.go#L60
