### ISSUE TITLE
Unable to retrieve loukoum v3

### ISSUE THREAD

**Issue by thoas** [ulule/loukoum#74]
```console
go get -v github.com/ulule/loukoum@v3.0.0
go: github.com/ulule/loukoum@v0.0.0-20190206082431-ec2137ea2ea9: go.mod has post-v0 module path "github.com/ulule/loukoum/v3" at revision ec2137ea2ea9
go: error loading module requirements
```

Needs investigation, maybe we will have to rollback this change as it will also break makroud.

**Comment by thoas** [comment]
It works with `go get github.com/ulule/loukoum/v3`.

**Comment by novln** [comment]
Makroud still uses `dep`, and `dep` and go modules are incompatible last I checked if you have the version in the import path. I'll migrate makroud to `go modules` since loukoum use it now.

**Comment by thoas** [comment]
closing this issue, since it's completely not related to loukoum and I was to dumb to know how to really use `go modules`.
